import api from "../api";

/* =========================================================
   DOCUMENT LAYOUTS
   ========================================================= */

export const DOCUMENT_LAYOUTS = [
  "risk_register",
  "detailed_evidence",
  "summary",
] as const;

export type DocumentLayout =
  (typeof DOCUMENT_LAYOUTS)[number];

/* =========================================================
   DOCUMENT FORMATS
   ========================================================= */

export const DOCUMENT_FORMATS = [
  "pdf",
  "docx",
  "xlsx",
] as const;

export type DocumentFormat =
  (typeof DOCUMENT_FORMATS)[number];

/* =========================================================
   DOCUMENT STATUS
   ========================================================= */

export const DOCUMENT_STATUSES = [
  "generating",
  "completed",
  "failed",
] as const;

export type DocumentStatus =
  (typeof DOCUMENT_STATUSES)[number];

/* =========================================================
   RISK STATUS FILTER
   ========================================================= */

export const DOCUMENT_RISK_STATUS_FILTERS = [
  "all",
  "in_progress",
  "complete",
] as const;

export type DocumentRiskStatusFilter =
  (typeof DOCUMENT_RISK_STATUS_FILTERS)[number];

/* =========================================================
   RISK SORTING
   ========================================================= */

export const DOCUMENT_RISK_SORT_FIELDS = [
  "serialNo",
  "createdAt",
  "updatedAt",
  "status",
] as const;

export type DocumentRiskSortField =
  (typeof DOCUMENT_RISK_SORT_FIELDS)[number];

/* =========================================================
   DOCUMENT HISTORY SORTING
   ========================================================= */

export const DOCUMENT_SORT_FIELDS = [
  "createdAt",
  "generatedAt",
  "title",
  "status",
  "format",
  "layout",
] as const;

export type DocumentSortField =
  (typeof DOCUMENT_SORT_FIELDS)[number];

/* =========================================================
   DOCUMENT FILTERS
   ========================================================= */

export type DocumentFilters = {
  statusFilter: DocumentRiskStatusFilter;

  includeProjectDetails: boolean;

  includeRiskRegisterId: boolean;

  includeBeforeEvidence: boolean;

  includeAfterEvidence: boolean;

  includeEvidenceImages: boolean;

  dateFrom?: string;

  dateTo?: string;

  selectedRiskIds: string[];

  sortBy: DocumentRiskSortField;

  sortOrder: "asc" | "desc";
};

/* =========================================================
   DOCUMENT SUMMARY
   ========================================================= */

export type DocumentSummary = {
  totalRisks: number;

  inProgressRisks: number;

  completeRisks: number;

  beforeEvidenceCount: number;

  afterEvidenceCount: number;

  totalEvidenceCount: number;

  completionPercentage: number;
};

/* =========================================================
   GENERATED BY USER
   ========================================================= */

export type DocumentGeneratedByUser = {
  _id: string;

  name?: string;

  email?: string;

  role?: string;

  avatar?: string;
};

export type DocumentGeneratedBy =
  | string
  | DocumentGeneratedByUser
  | null;

/* =========================================================
   MAIN DOCUMENT TYPE
   ========================================================= */

export type ProjectDocumentRecord = {
  _id: string;

  projectId: string;

  /*
    Backend database field projectCode hai.

    Frontend par Project Reference Number ke label ke saath
    display hoga.
  */
  projectCode: string;

  projectReferenceNo: string;

  projectTitle: string;

  title: string;

  description?: string;

  layout: DocumentLayout;

  format: DocumentFormat;

  status: DocumentStatus;

  filters: DocumentFilters;

  exportedRiskIds: string[];

  summary: DocumentSummary;

  fileName?: string;

  filePath?: string;

  mimeType?: string;

  fileSize?: number;

  generatedAt?: string;

  generatedBy: DocumentGeneratedBy;

  failureReason?: string;

  createdAt: string;

  updatedAt: string;
};

/* =========================================================
   GENERATE DOCUMENT PAYLOAD
   ========================================================= */

export type GenerateDocumentFiltersPayload = {
  statusFilter?: DocumentRiskStatusFilter;

  includeProjectDetails?: boolean;

  includeRiskRegisterId?: boolean;

  includeBeforeEvidence?: boolean;

  includeAfterEvidence?: boolean;

  includeEvidenceImages?: boolean;

  dateFrom?: string;

  dateTo?: string;

  selectedRiskIds?: string[];

  sortBy?: DocumentRiskSortField;

  sortOrder?: "asc" | "desc";
};

export type GenerateDocumentPayload = {
  projectId: string;

  title: string;

  description?: string;

  layout?: DocumentLayout;

  format: DocumentFormat;

  filters?: GenerateDocumentFiltersPayload;
};

/* =========================================================
   GENERATION RESULT
   ========================================================= */

export type GenerateDocumentResult = {
  document: ProjectDocumentRecord;

  exportedRecords: number;
};

/* =========================================================
   DOCUMENT LIST PARAMETERS
   ========================================================= */

export type DocumentListParams = {
  projectId?: string;

  search?: string;

  layout?: DocumentLayout | "";

  format?: DocumentFormat | "";

  status?: DocumentStatus | "";

  generatedBy?: string;

  dateFrom?: string;

  dateTo?: string;

  page?: number;

  limit?: number;

  sortBy?: DocumentSortField;

  sortOrder?: "asc" | "desc";
};

/* =========================================================
   PAGINATION
   ========================================================= */

export type DocumentPagination = {
  page: number;

  limit: number;

  total: number;

  totalPages: number;

  hasPreviousPage: boolean;

  hasNextPage: boolean;
};

export type DocumentListResult = {
  documents: ProjectDocumentRecord[];

  pagination: DocumentPagination;
};

/* =========================================================
   SINGLE DOCUMENT RESULT
   ========================================================= */

export type DocumentDetailsResult = {
  document: ProjectDocumentRecord;
};

/* =========================================================
   DELETE RESULT
   ========================================================= */

export type DeleteDocumentResult = {
  document: ProjectDocumentRecord;

  fileDeleted: boolean;
};

/* =========================================================
   DOWNLOAD RESULT
   ========================================================= */

export type DownloadDocumentResult = {
  blob: Blob;

  fileName: string;

  mimeType: string;
};

/* =========================================================
   INTERNAL API TYPES
   ========================================================= */

type ApiEnvelope<T> = {
  success?: boolean;

  message?: string;

  data?: T;
};

type RawDocumentListData = {
  documents?: unknown[];

  pagination?: unknown;
};

/* =========================================================
   GENERAL HELPERS
   ========================================================= */

const hasOwnField = (
  object: object,
  field: PropertyKey
): boolean => {
  return Object.prototype.hasOwnProperty.call(
    object,
    field
  );
};

const normalizeString = (
  value: unknown
): string => {
  return typeof value === "string"
    ? value
    : "";
};

const normalizeTrimmedString = (
  value: unknown
): string => {
  return normalizeString(
    value
  ).trim();
};

const normalizeNumber = (
  value: unknown,
  fallback = 0
): number => {
  const numberValue =
    Number(value);

  return Number.isFinite(
    numberValue
  )
    ? numberValue
    : fallback;
};

const normalizeNonNegativeNumber = (
  value: unknown,
  fallback = 0
): number => {
  return Math.max(
    normalizeNumber(
      value,
      fallback
    ),
    0
  );
};

const normalizeNonNegativeInteger = (
  value: unknown,
  fallback = 0
): number => {
  return Math.max(
    Math.trunc(
      normalizeNumber(
        value,
        fallback
      )
    ),
    0
  );
};

const encodePathValue = (
  value: string
): string => {
  return encodeURIComponent(
    value.trim()
  );
};

/* =========================================================
   RESPONSE DATA EXTRACTOR
   ========================================================= */

const extractResponseData = <T>(
  response: unknown
): T => {
  const axiosResponse =
    response as {
      data?: unknown;
    };

  const responseBody =
    axiosResponse?.data;

  if (
    responseBody &&
    typeof responseBody ===
      "object" &&
    "data" in responseBody
  ) {
    const envelope =
      responseBody as ApiEnvelope<T>;

    if (
      envelope.data !==
      undefined
    ) {
      return envelope.data;
    }
  }

  return responseBody as T;
};

/* =========================================================
   ENUM NORMALIZERS
   ========================================================= */

const normalizeDocumentLayout = (
  value: unknown
): DocumentLayout => {
  return DOCUMENT_LAYOUTS.includes(
    value as DocumentLayout
  )
    ? (value as DocumentLayout)
    : "risk_register";
};

const normalizeDocumentFormat = (
  value: unknown
): DocumentFormat => {
  return DOCUMENT_FORMATS.includes(
    value as DocumentFormat
  )
    ? (value as DocumentFormat)
    : "pdf";
};

const normalizeDocumentStatus = (
  value: unknown
): DocumentStatus => {
  return DOCUMENT_STATUSES.includes(
    value as DocumentStatus
  )
    ? (value as DocumentStatus)
    : "generating";
};

const normalizeRiskStatusFilter = (
  value: unknown
): DocumentRiskStatusFilter => {
  return DOCUMENT_RISK_STATUS_FILTERS.includes(
    value as DocumentRiskStatusFilter
  )
    ? (value as DocumentRiskStatusFilter)
    : "all";
};

const normalizeRiskSortField = (
  value: unknown
): DocumentRiskSortField => {
  return DOCUMENT_RISK_SORT_FIELDS.includes(
    value as DocumentRiskSortField
  )
    ? (value as DocumentRiskSortField)
    : "serialNo";
};

/* =========================================================
   STRING ARRAY NORMALIZER
   ========================================================= */

const normalizeStringArray = (
  value: unknown
): string[] => {
  if (!Array.isArray(value)) {
    return [];
  }

  return [
    ...new Set(
      value
        .map(
          normalizeTrimmedString
        )
        .filter(Boolean)
    ),
  ];
};

/* =========================================================
   DOCUMENT FILTER NORMALIZER
   ========================================================= */

const normalizeDocumentFilters = (
  rawFilters: unknown
): DocumentFilters => {
  const filters =
    rawFilters &&
    typeof rawFilters ===
      "object"
      ? (
          rawFilters as Partial<DocumentFilters>
        )
      : {};

  const dateFrom =
    normalizeTrimmedString(
      filters.dateFrom
    );

  const dateTo =
    normalizeTrimmedString(
      filters.dateTo
    );

  return {
    statusFilter:
      normalizeRiskStatusFilter(
        filters.statusFilter
      ),

    includeProjectDetails:
      typeof filters
        .includeProjectDetails ===
      "boolean"
        ? filters.includeProjectDetails
        : true,

    includeRiskRegisterId:
      typeof filters
        .includeRiskRegisterId ===
      "boolean"
        ? filters.includeRiskRegisterId
        : true,

    includeBeforeEvidence:
      typeof filters
        .includeBeforeEvidence ===
      "boolean"
        ? filters.includeBeforeEvidence
        : true,

    includeAfterEvidence:
      typeof filters
        .includeAfterEvidence ===
      "boolean"
        ? filters.includeAfterEvidence
        : true,

    includeEvidenceImages:
      typeof filters
        .includeEvidenceImages ===
      "boolean"
        ? filters.includeEvidenceImages
        : true,

    ...(dateFrom
      ? {
          dateFrom,
        }
      : {}),

    ...(dateTo
      ? {
          dateTo,
        }
      : {}),

    selectedRiskIds:
      normalizeStringArray(
        filters.selectedRiskIds
      ),

    sortBy:
      normalizeRiskSortField(
        filters.sortBy
      ),

    sortOrder:
      filters.sortOrder ===
      "desc"
        ? "desc"
        : "asc",
  };
};

/* =========================================================
   SUMMARY NORMALIZER
   ========================================================= */

const normalizeDocumentSummary = (
  rawSummary: unknown
): DocumentSummary => {
  const summary =
    rawSummary &&
    typeof rawSummary ===
      "object"
      ? (
          rawSummary as Partial<DocumentSummary>
        )
      : {};

  const beforeEvidenceCount =
    normalizeNonNegativeInteger(
      summary.beforeEvidenceCount
    );

  const afterEvidenceCount =
    normalizeNonNegativeInteger(
      summary.afterEvidenceCount
    );

  return {
    totalRisks:
      normalizeNonNegativeInteger(
        summary.totalRisks
      ),

    inProgressRisks:
      normalizeNonNegativeInteger(
        summary.inProgressRisks
      ),

    completeRisks:
      normalizeNonNegativeInteger(
        summary.completeRisks
      ),

    beforeEvidenceCount,

    afterEvidenceCount,

    totalEvidenceCount:
      normalizeNonNegativeInteger(
        summary.totalEvidenceCount,
        beforeEvidenceCount +
          afterEvidenceCount
      ),

    completionPercentage:
      Math.min(
        normalizeNonNegativeNumber(
          summary.completionPercentage
        ),
        100
      ),
  };
};

/* =========================================================
   GENERATED BY NORMALIZER
   ========================================================= */

const normalizeGeneratedBy = (
  value: unknown
): DocumentGeneratedBy => {
  if (
    typeof value === "string"
  ) {
    return value.trim();
  }

  if (
    value &&
    typeof value ===
      "object"
  ) {
    const user =
      value as Partial<DocumentGeneratedByUser>;

    return {
      _id:
        normalizeTrimmedString(
          user._id
        ),

      ...(normalizeTrimmedString(
        user.name
      )
        ? {
            name:
              normalizeTrimmedString(
                user.name
              ),
          }
        : {}),

      ...(normalizeTrimmedString(
        user.email
      )
        ? {
            email:
              normalizeTrimmedString(
                user.email
              ),
          }
        : {}),

      ...(normalizeTrimmedString(
        user.role
      )
        ? {
            role:
              normalizeTrimmedString(
                user.role
              ),
          }
        : {}),

      ...(normalizeTrimmedString(
        user.avatar
      )
        ? {
            avatar:
              normalizeTrimmedString(
                user.avatar
              ),
          }
        : {}),
    };
  }

  return null;
};

/* =========================================================
   DOCUMENT NORMALIZER
   ========================================================= */

const normalizeDocument = (
  rawDocument: unknown
): ProjectDocumentRecord => {
  const document =
    rawDocument &&
    typeof rawDocument ===
      "object"
      ? (
          rawDocument as Partial<ProjectDocumentRecord>
        )
      : {};

  const projectCode =
    normalizeTrimmedString(
      document.projectCode
    );

  const projectReferenceNo =
    normalizeTrimmedString(
      document.projectReferenceNo
    ) || projectCode;

  const description =
    normalizeTrimmedString(
      document.description
    );

  const fileName =
    normalizeTrimmedString(
      document.fileName
    );

  const filePath =
    normalizeTrimmedString(
      document.filePath
    );

  const mimeType =
    normalizeTrimmedString(
      document.mimeType
    );

  const generatedAt =
    normalizeTrimmedString(
      document.generatedAt
    );

  const failureReason =
    normalizeTrimmedString(
      document.failureReason
    );

  return {
    _id:
      normalizeTrimmedString(
        document._id
      ),

    projectId:
      normalizeTrimmedString(
        document.projectId
      ),

    projectCode,

    projectReferenceNo,

    projectTitle:
      normalizeTrimmedString(
        document.projectTitle
      ),

    title:
      normalizeTrimmedString(
        document.title
      ),

    ...(description
      ? {
          description,
        }
      : {}),

    layout:
      normalizeDocumentLayout(
        document.layout
      ),

    format:
      normalizeDocumentFormat(
        document.format
      ),

    status:
      normalizeDocumentStatus(
        document.status
      ),

    filters:
      normalizeDocumentFilters(
        document.filters
      ),

    exportedRiskIds:
      normalizeStringArray(
        document.exportedRiskIds
      ),

    summary:
      normalizeDocumentSummary(
        document.summary
      ),

    ...(fileName
      ? {
          fileName,
        }
      : {}),

    ...(filePath
      ? {
          filePath,
        }
      : {}),

    ...(mimeType
      ? {
          mimeType,
        }
      : {}),

    ...(document.fileSize !==
    undefined
      ? {
          fileSize:
            normalizeNonNegativeInteger(
              document.fileSize
            ),
        }
      : {}),

    ...(generatedAt
      ? {
          generatedAt,
        }
      : {}),

    generatedBy:
      normalizeGeneratedBy(
        document.generatedBy
      ),

    ...(failureReason
      ? {
          failureReason,
        }
      : {}),

    createdAt:
      normalizeTrimmedString(
        document.createdAt
      ),

    updatedAt:
      normalizeTrimmedString(
        document.updatedAt
      ),
  };
};

/* =========================================================
   PAGINATION NORMALIZER
   ========================================================= */

const normalizePagination = (
  rawPagination: unknown,
  documentCount: number
): DocumentPagination => {
  const pagination =
    rawPagination &&
    typeof rawPagination ===
      "object"
      ? (
          rawPagination as Partial<DocumentPagination>
        )
      : {};

  const page =
    Math.max(
      normalizeNonNegativeInteger(
        pagination.page,
        1
      ),
      1
    );

  const limit =
    Math.max(
      normalizeNonNegativeInteger(
        pagination.limit,
        documentCount || 1
      ),
      1
    );

  const total =
    normalizeNonNegativeInteger(
      pagination.total,
      documentCount
    );

  const totalPages =
    Math.max(
      normalizeNonNegativeInteger(
        pagination.totalPages,
        Math.ceil(
          total / limit
        ) || 1
      ),
      1
    );

  return {
    page,

    limit,

    total,

    totalPages,

    hasPreviousPage:
      typeof pagination
        .hasPreviousPage ===
      "boolean"
        ? pagination.hasPreviousPage
        : page > 1,

    hasNextPage:
      typeof pagination
        .hasNextPage ===
      "boolean"
        ? pagination.hasNextPage
        : page < totalPages,
  };
};

/* =========================================================
   DOCUMENT LIST NORMALIZER
   ========================================================= */

const normalizeDocumentListResult = (
  data: unknown
): DocumentListResult => {
  if (Array.isArray(data)) {
    const documents =
      data.map(
        normalizeDocument
      );

    return {
      documents,

      pagination:
        normalizePagination(
          undefined,
          documents.length
        ),
    };
  }

  const listData =
    data &&
    typeof data ===
      "object"
      ? (
          data as RawDocumentListData
        )
      : {};

  const documents =
    Array.isArray(
      listData.documents
    )
      ? listData.documents.map(
          normalizeDocument
        )
      : [];

  return {
    documents,

    pagination:
      normalizePagination(
        listData.pagination,
        documents.length
      ),
  };
};

/* =========================================================
   SINGLE DOCUMENT EXTRACTOR
   ========================================================= */

const extractDocument = (
  data: unknown
): ProjectDocumentRecord => {
  if (
    data &&
    typeof data ===
      "object" &&
    "document" in data
  ) {
    return normalizeDocument(
      (
        data as {
          document?: unknown;
        }
      ).document
    );
  }

  return normalizeDocument(
    data
  );
};

/* =========================================================
   GENERATE PAYLOAD PREPARATION
   ========================================================= */

const prepareGeneratePayload = (
  payload: GenerateDocumentPayload
) => {
  const projectId =
    payload.projectId.trim();

  const title =
    payload.title.trim();

  const description =
    payload.description
      ?.trim();

  const filters =
    payload.filters;

  const preparedFilters:
    Record<string, unknown> = {};

  if (filters) {
    if (
      hasOwnField(
        filters,
        "statusFilter"
      )
    ) {
      preparedFilters.statusFilter =
        filters.statusFilter;
    }

    if (
      hasOwnField(
        filters,
        "includeProjectDetails"
      )
    ) {
      preparedFilters.includeProjectDetails =
        filters.includeProjectDetails;
    }

    if (
      hasOwnField(
        filters,
        "includeRiskRegisterId"
      )
    ) {
      preparedFilters.includeRiskRegisterId =
        filters.includeRiskRegisterId;
    }

    if (
      hasOwnField(
        filters,
        "includeBeforeEvidence"
      )
    ) {
      preparedFilters.includeBeforeEvidence =
        filters.includeBeforeEvidence;
    }

    if (
      hasOwnField(
        filters,
        "includeAfterEvidence"
      )
    ) {
      preparedFilters.includeAfterEvidence =
        filters.includeAfterEvidence;
    }

    if (
      hasOwnField(
        filters,
        "includeEvidenceImages"
      )
    ) {
      preparedFilters.includeEvidenceImages =
        filters.includeEvidenceImages;
    }

    if (
      filters.dateFrom?.trim()
    ) {
      preparedFilters.dateFrom =
        filters.dateFrom.trim();
    }

    if (
      filters.dateTo?.trim()
    ) {
      preparedFilters.dateTo =
        filters.dateTo.trim();
    }

    if (
      Array.isArray(
        filters.selectedRiskIds
      )
    ) {
      preparedFilters.selectedRiskIds =
        [
          ...new Set(
            filters.selectedRiskIds
              .map((riskId) =>
                riskId.trim()
              )
              .filter(Boolean)
          ),
        ];
    }

    if (filters.sortBy) {
      preparedFilters.sortBy =
        filters.sortBy;
    }

    if (filters.sortOrder) {
      preparedFilters.sortOrder =
        filters.sortOrder;
    }
  }

  return {
    projectId,

    title,

    ...(description
      ? {
          description,
        }
      : {}),

    layout:
      payload.layout ||
      "risk_register",

    format:
      payload.format,

    ...(Object.keys(
      preparedFilters
    ).length > 0
      ? {
          filters:
            preparedFilters,
        }
      : {}),
  };
};

/* =========================================================
   LIST QUERY PREPARATION
   ========================================================= */

const prepareListParams = (
  params: DocumentListParams = {}
) => {
  return {
    ...(params.projectId
      ?.trim()
      ? {
          projectId:
            params.projectId.trim(),
        }
      : {}),

    ...(params.search?.trim()
      ? {
          search:
            params.search.trim(),
        }
      : {}),

    ...(params.layout
      ? {
          layout:
            params.layout,
        }
      : {}),

    ...(params.format
      ? {
          format:
            params.format,
        }
      : {}),

    ...(params.status
      ? {
          status:
            params.status,
        }
      : {}),

    ...(params.generatedBy
      ?.trim()
      ? {
          generatedBy:
            params.generatedBy.trim(),
        }
      : {}),

    ...(params.dateFrom
      ?.trim()
      ? {
          dateFrom:
            params.dateFrom.trim(),
        }
      : {}),

    ...(params.dateTo
      ?.trim()
      ? {
          dateTo:
            params.dateTo.trim(),
        }
      : {}),

    ...(params.page
      ? {
          page:
            params.page,
        }
      : {}),

    ...(params.limit
      ? {
          limit:
            params.limit,
        }
      : {}),

    ...(params.sortBy
      ? {
          sortBy:
            params.sortBy,
        }
      : {}),

    ...(params.sortOrder
      ? {
          sortOrder:
            params.sortOrder,
        }
      : {}),
  };
};

/* =========================================================
   GENERATE DOCUMENT

   POST /documents/generate
   ========================================================= */

export const generateDocument = async (
  payload: GenerateDocumentPayload
): Promise<GenerateDocumentResult> => {
  const response =
    await api.post(
      "/documents/generate",
      prepareGeneratePayload(
        payload
      )
    );

  const data =
    extractResponseData<unknown>(
      response
    );

  const result =
    data &&
    typeof data ===
      "object"
      ? (
          data as {
            document?: unknown;

            exportedRecords?: unknown;
          }
        )
      : {};

  return {
    document:
      normalizeDocument(
        result.document
      ),

    exportedRecords:
      normalizeNonNegativeInteger(
        result.exportedRecords
      ),
  };
};

/* =========================================================
   GET DOCUMENT HISTORY

   GET /documents
   ========================================================= */

export const getDocuments = async (
  params: DocumentListParams = {}
): Promise<DocumentListResult> => {
  const response =
    await api.get(
      "/documents",
      {
        params:
          prepareListParams(
            params
          ),
      }
    );

  const data =
    extractResponseData<unknown>(
      response
    );

  return normalizeDocumentListResult(
    data
  );
};

/* =========================================================
   GET PROJECT DOCUMENT HISTORY

   GET /documents/project/:projectId
   ========================================================= */

export const getDocumentsByProject =
  async (
    projectId: string,
    params: Omit<
      DocumentListParams,
      "projectId"
    > = {}
  ): Promise<DocumentListResult> => {
    const response =
      await api.get(
        `/documents/project/${encodePathValue(
          projectId
        )}`,
        {
          params:
            prepareListParams(
              params
            ),
        }
      );

    const data =
      extractResponseData<unknown>(
        response
      );

    return normalizeDocumentListResult(
      data
    );
  };

/* =========================================================
   GET SINGLE DOCUMENT

   GET /documents/:documentId
   ========================================================= */

export const getDocumentById =
  async (
    documentId: string
  ): Promise<ProjectDocumentRecord> => {
    const response =
      await api.get(
        `/documents/${encodePathValue(
          documentId
        )}`
      );

    const data =
      extractResponseData<unknown>(
        response
      );

    return extractDocument(
      data
    );
  };

/* =========================================================
   DOWNLOAD DOCUMENT

   GET /documents/:documentId/download
   ========================================================= */

export const downloadDocument =
  async (
    documentId: string
  ): Promise<DownloadDocumentResult> => {
    const response =
      await api.get(
        `/documents/${encodePathValue(
          documentId
        )}/download`,
        {
          responseType:
            "blob",
        }
      );

    const blob =
      response.data instanceof Blob
        ? response.data
        : new Blob([
            response.data,
          ]);

    const contentType =
      normalizeTrimmedString(
        response.headers?.[
          "content-type"
        ]
      ) ||
      blob.type ||
      "application/octet-stream";

    const contentDisposition =
      normalizeTrimmedString(
        response.headers?.[
          "content-disposition"
        ]
      );

    let fileName =
      "project-report";

    const utf8FileNameMatch =
      contentDisposition.match(
        /filename\*=UTF-8''([^;]+)/i
      );

    const normalFileNameMatch =
      contentDisposition.match(
        /filename="?([^";]+)"?/i
      );

    if (
      utf8FileNameMatch?.[1]
    ) {
      try {
        fileName =
          decodeURIComponent(
            utf8FileNameMatch[1]
          );
      } catch {
        fileName =
          utf8FileNameMatch[1];
      }
    } else if (
      normalFileNameMatch?.[1]
    ) {
      fileName =
        normalFileNameMatch[1];
    }

    return {
      blob,

      fileName:
        fileName.trim(),

      mimeType:
        contentType,
    };
  };

/* =========================================================
   DOWNLOAD AND SAVE IN BROWSER

   UI button directly is helper ko call kar sakta hai.
   ========================================================= */

export const saveDocumentDownload =
  async (
    documentId: string
  ): Promise<void> => {
    const {
      blob,
      fileName,
    } =
      await downloadDocument(
        documentId
      );

    const objectUrl =
      URL.createObjectURL(
        blob
      );

    const anchor =
      window.document.createElement(
        "a"
      );

    anchor.href =
      objectUrl;

    anchor.download =
      fileName;

    anchor.style.display =
      "none";

    window.document.body.appendChild(
      anchor
    );

    anchor.click();

    anchor.remove();

    URL.revokeObjectURL(
      objectUrl
    );
  };

/* =========================================================
   DELETE DOCUMENT

   DELETE /documents/:documentId

   Generated file aur history record remove honge.

   Original Project, Risks aur Evidence affect nahi honge.
   ========================================================= */

export const deleteDocument =
  async (
    documentId: string
  ): Promise<DeleteDocumentResult> => {
    const response =
      await api.delete(
        `/documents/${encodePathValue(
          documentId
        )}`
      );

    const data =
      extractResponseData<unknown>(
        response
      );

    const result =
      data &&
      typeof data ===
        "object"
        ? (
            data as {
              document?: unknown;

              fileDeleted?: unknown;
            }
          )
        : {};

    return {
      document:
        normalizeDocument(
          result.document
        ),

      fileDeleted:
        result.fileDeleted ===
        true,
    };
  };

/* =========================================================
   DISPLAY HELPERS
   ========================================================= */

export const getDocumentProjectReference =
  (
    document: Pick<
      ProjectDocumentRecord,
      | "projectCode"
      | "projectReferenceNo"
    >
  ): string => {
    return (
      document.projectReferenceNo
        ?.trim() ||
      document.projectCode.trim()
    );
  };

export const getDocumentGeneratedByName =
  (
    document: Pick<
      ProjectDocumentRecord,
      "generatedBy"
    >
  ): string => {
    const generatedBy =
      document.generatedBy;

    if (
      typeof generatedBy ===
      "string"
    ) {
      return generatedBy;
    }

    return (
      generatedBy?.name?.trim() ||
      generatedBy?.email?.trim() ||
      "—"
    );
  };

export const getDocumentStatusLabel =
  (
    status: DocumentStatus
  ): string => {
    if (
      status === "completed"
    ) {
      return "Completed";
    }

    if (
      status === "failed"
    ) {
      return "Failed";
    }

    return "Generating";
  };

export const getDocumentLayoutLabel =
  (
    layout: DocumentLayout
  ): string => {
    if (
      layout ===
      "detailed_evidence"
    ) {
      return "Detailed Evidence";
    }

    if (
      layout ===
      "summary"
    ) {
      return "Summary";
    }

    return "Risk Register";
  };

export const getDocumentFormatLabel =
  (
    format: DocumentFormat
  ): string => {
    return format.toUpperCase();
  };

export const formatDocumentFileSize =
  (
    bytes?: number
  ): string => {
    const fileSize =
      normalizeNonNegativeNumber(
        bytes
      );

    if (
      fileSize <= 0
    ) {
      return "—";
    }

    if (
      fileSize < 1024
    ) {
      return `${Math.round(
        fileSize
      )} B`;
    }

    const kilobytes =
      fileSize / 1024;

    if (
      kilobytes < 1024
    ) {
      return `${kilobytes.toFixed(
        1
      )} KB`;
    }

    const megabytes =
      kilobytes / 1024;

    if (
      megabytes < 1024
    ) {
      return `${megabytes.toFixed(
        1
      )} MB`;
    }

    const gigabytes =
      megabytes / 1024;

    return `${gigabytes.toFixed(
      2
    )} GB`;
  };